### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xsung** [xsung/blog-dev#1]
## 待集成的模块

- [ ] source/gitbooks  整合的blog
- [ ] source/slides    online-slides功能
- [ ] souce/tutorial/ 集成jupyter notebook功能
- [ ] souce/demo/
  - [ ] souce/demo/onlineTex   参考jaxTex sharelatex
  - [ ] souce/demo/onlineMarkdown  参考jaxMark
  - [ ] souce/demo/onlineMarkdown  参考jaxMark
  - [ ] flappy bird   --- AI
  - [ ] breakout
  - [ ] chess
  - [ ] go
  - [ ] online embedding   --- text
  - [ ] online chat system
  - [ ] online classification with resnet   -- vision
  - [ ] online object detection

## theme 可视化

- [ ] tag cloud 代替目前标签，并一直显示。归档tree可以在导航栏
- [ ] dd
- [ ] 统计量采用图标，hover出text，http://www.liangxiansen.cn/tags/  需要加个title即可

## 归档 & 标签 关键词

效率 --  代替工具

**Comment by xu-song** [comment]
<a href="javascript:;" onclick="pop_show(event, '迷失的骆驼');" class="copy">查看答案</a>

**Comment by xu-song** [comment]
<figure>
 <img src="http://placekitten.com/200/300" alt="Small picture of a kitten" />
 <figcaption>
 Small picture of a kitten, graciously shared by <a href="http://placekitten.com">placekitten.com</a>
 </figcaption>
</figure>

 Small picture of a kitten, graciously shar

fadfd
## fdfd

**Comment by xu-song** [comment]
| No. | Time     | Source                    | Destination     | Protocol | Length | Info                                                                                                               |                                                                            |              |
|-----|----------|---------------------------|-----------------|----------|--------|--------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------|--------------|
| 1   | 0        | Cisco_a7:0c:20            | Broadcast       | ARP      | 42     | Gratuitous ARP for 9.186.58.27 (Reply)                                                                             |                                                                            |              |
| 2   | 3.857586 | 9.186.60.93               | 9.186.60.255    | BROWSER  | 258    | "Domain/Workgroup Announcement WORKGROUP                                                                           | NT Workstation                                                             | Domain Enum" |
| 3   | 5.576989 | Cisco_a7:0c:20            | Broadcast       | ARP      | 42     | Gratuitous ARP for 9.186.58.29 (Reply)                                                                             |                                                                            |              |
| 4   | 5.992808 | 9.186.60.93               | 9.186.88.5      | DNS      | 73     | Standard query 0x816e A www.baidu.com                                                                              |                                                                            |              |
| 5   | 6.006752 | 9.186.88.5                | 9.186.60.93     | DNS      | 132    | Standard query response 0x816e A www.baidu.com CNAME www.a.shifen.com A 220.181.112.244 A 220.181.111.188          |                                                                            |              |
| 6   | 6.008707 | 9.186.60.93               | 9.186.88.5      | DNS      | 73     | Standard query 0xd8a8 AAAA www.baidu.com                                                                           |                                                                            |              |
| 7   | 6.040605 | 9.186.60.93               | 9.186.88.5      | DNS      | 73     | Standard query 0xd8a8 AAAA www.baidu.com                                                                           |                                                                            |              |
| 8   | 6.071909 | 9.186.60.93               | 9.186.88.5      | DNS      | 73     | Standard query 0xd8a8 AAAA www.baidu.com                                                                           |                                                                            |              |
| 9   | 6.13377  | 9.186.88.5                | 9.186.60.93     | DNS      | 183    | Standard query response 0xd8a8 AAAA www.baidu.com CNAME www.a.shifen.com CNAME www.wshifen.com SOA ns1.wshifen.com |                                                                            |              |
| 10  | 6.278011 | 9.186.60.93               | 220.181.112.244 | TCP      | 66     | 59258  >  80 [SYN] Seq=0 Win=8192 Len=0 MSS=1460 WS=4 SACK_PERM=1                                                  |                                                                            |              |
| 11  | 6.286044 | 220.181.112.244           | 9.186.60.93     | TCP      | 66     | "80  >  59258 [SYN                                                                                                 | ACK] Seq=0 Ack=1 Win=1380 Len=0 MSS=1380 WS=32 SACK_PERM=1"                |              |
| 12  | 6.286566 | 9.186.60.93               | 220.181.112.244 | TCP      | 54     | 59258  >  80 [ACK] Seq=1 Ack=1 Win=16560 Len=0                                                                     |                                                                            |              |
| 13  | 6.288227 | 9.186.60.93               | 220.181.112.244 | HTTP     | 131    | GET / HTTP/1.1                                                                                                     |                                                                            |              |
| 14  | 6.2993   | 220.181.112.244           | 9.186.60.93     | TCP      | 54     | 80  >  59258 [ACK] Seq=1 Ack=78 Win=24704 Len=0                                                                    |                                                                            |              |
| 15  | 6.299362 | 220.181.112.244           | 9.186.60.93     | TCP      | 454    | "80  >  59258 [PSH                                                                                                 | ACK] Seq=1 Ack=78 Win=24704 Len=400 [TCP segment of a reassembled PDU]"    |              |
| 16  | 6.299664 | 220.181.112.244           | 9.186.60.93     | TCP      | 1094   | "80  >  59258 [PSH                                                                                                 | ACK] Seq=401 Ack=78 Win=24704 Len=1040 [TCP segment of a reassembled PDU]" |              |
| 17  | 6.300057 | 220.181.112.244           | 9.186.60.93     | HTTP     | 1395   | HTTP/1.1 200 OK  (text/html)                                                                                       |                                                                            |              |
| 18  | 6.300447 | 220.181.112.244           | 9.186.60.93     | TCP      | 54     | "80  >  59258 [FIN                                                                                                 | ACK] Seq=2782 Ack=78 Win=24704 Len=0"                                      |              |
| 19  | 6.300603 | 9.186.60.93               | 220.181.112.244 | TCP      | 54     | 59258  >  80 [ACK] Seq=78 Ack=1441 Win=16560 Len=0                                                                 |                                                                            |              |
| 20  | 6.30078  | 9.186.60.93               | 220.181.112.244 | TCP      | 54     | 59258  >  80 [ACK] Seq=78 Ack=2783 Win=15216 Len=0                                                                 |                                                                            |              |
| 21  | 6.330305 | 9.186.60.93               | 220.181.112.244 | TCP      | 54     | "59258  >  80 [FIN                                                                                                 | ACK] Seq=78 Ack=2783 Win=15216 Len=0"                                      |              |
| 22  | 6.339982 | 220.181.112.244           | 9.186.60.93     | TCP      | 54     | 80  >  59258 [ACK] Seq=2783 Ack=79 Win=24704 Len=0                                                                 |                                                                            |              |
| 23  | 7.421653 | 34.193.43.235             | 9.186.60.93     | TLSv1.2  | 85     | Application Data                                                                                                   |                                                                            |              |
| 24  | 7.422409 | 9.186.60.93               | 34.193.43.235   | TLSv1.2  | 89     | Application Data                                                                                                   |                                                                            |              |
| 25  | 7.459662 | 34.193.43.235             | 9.186.60.93     | TCP      | 54     | 443  >  55209 [ACK] Seq=32 Ack=36 Win=253 Len=0                                                                    |                                                                            |              |
| 26  | 8.004601 | Cisco_a7:0c:20            | Broadcast       | ARP      | 42     | Gratuitous ARP for 9.186.58.24 (Reply)                                                                             |                                                                            |              |
| 27  | 8.035896 | fe80::dcfa:89ef:d5a3:26c8 | ff02::1:2       | DHCPv6   | 157    | Solicit XID: 0x708d06 CID: 000100011d3fb28a68f72836446e                                                            |                                                                            |              |
| 28  | 8.199566 | 9.186.60.93               | 9.186.88.5      | DNS      | 75     | Standard query 0x5f7e A wpad.cn.ibm.com                                                                            |                                                                            |              |
| 29  | 8.203708 | 9.186.88.5                | 9.186.60.93     | DNS      | 156    | Standard query response 0x5f7e No such name A wpad.cn.ibm.com SOA j7on-ib-md01.sg.ibm.com                          |                                                                            |              |
| 30  | 8.205849 | 9.186.60.93               | 9.186.88.5      | DNS      | 75     | Standard query 0x9ea4 A wpad.hk.ibm.com                                                                            |                                                                            |              |
| 31  | 8.208024 | 9.186.88.5                | 9.186.60.93     | DNS      | 156    | Standard query response 0x9ea4 No such name A wpad.hk.ibm.com SOA j7on-ib-md01.sg.ibm.com                          |                                                                            |              |
| 32  | 8.210226 | 9.186.60.93               | 9.186.88.5      | DNS      | 75     | Standard query 0xd310 A wpad.tw.ibm.com                                                                            |                                                                            |              |
| 33  | 8.220904 | 9.186.88.5                | 9.186.60.93     | DNS      | 156    | Standard query response 0xd310 No such name A wpad.tw.ibm.com SOA j7on-ib-md01.sg.ibm.com                          |                                                                            |              |
| 34  | 8.223266 | 9.186.60.93               | 9.186.88.5      | DNS      | 75     | Standard query 0x161d A wpad.au.ibm.com                                                                            |                                                                            |              |
| 35  | 8.226349 | 9.186.88.5                | 9.186.60.93     | DNS      | 156    | Standard query response 0x161d No such name A wpad.au.ibm.com SOA c4pn-ib-md01.in.ibm.com                          |                                                                            |              |
| 36  | 8.228502 | 9.186.60.93               | 9.186.88.5      | DNS      | 72     | Standard query 0xa3fb A wpad.ibm.com                                                                               |                                                                            |              |
| 37  | 8.233109 | 9.186.88.5                | 9.186.60.93     | DNS      | 138    | Standard query response 0xa3fb No such name A wpad.ibm.com SOA plpn-ib-mdrt01.pok.ibm.com                          |                                                                            |              |
| 38  | 8.238411 | 9.186.60.93               | 255.255.255.255 | DHCP     | 342    | DHCP Inform   - Transaction ID 0x5419cdc4                                                                          |                                                                            |              |
| 39  | 8.245322 | 9.186.88.5                | 9.186.60.93     | DHCP     | 342    | DHCP ACK      - Transaction ID 0x5419cdc4                                                                          |                                                                            |              |
| 40  | 8.250032 | 9.186.88.5                | 9.186.60.93     | DHCP     | 342    | DHCP ACK      - Transaction ID 0x5419cdc4                                                                          |                                                                            |              |
| 41  | 8.250314 | 9.186.60.93               | 9.186.88.5      | ICMP     | 370    | Destination unreachable (Port unreachable)                                                                         |                                                                            |              |
| 42  | 8.256835 | 9.186.88.31               | 9.186.60.93     | DHCP     | 342    | DHCP ACK      - Transaction ID 0x5419cdc4                                                                          |                                                                            |              |
| 43  | 8.257127 | 9.186.60.93               | 9.186.88.31     | ICMP     | 370    | Destination unreachable (Port unreachable)                                                                         |                                                                            |              |
| 44  | 8.261117 | 9.186.88.31               | 9.186.60.93     | DHCP     | 342    | DHCP ACK      - Transaction ID 0x5419cdc4                                                                          |                                                                            |              |
| 45  | 8.261379 | 9.186.60.93               | 9.186.88.31     | ICMP     | 370    | Destination unreachable (Port unreachable)                                                                         |                                                                            |              |
| 46  | 8.779336 | Cisco_a7:0c:20            | Broadcast       | ARP      | 42     | Gratuitous ARP for 9.186.58.21 (Reply)                                                                             |                                                                            |              |
